spring.application.name=paymentservice

# ==========================
# Database Configuration
# ==========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# Hibernate / JPA
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==========================
# Server
# ==========================
server.port=8085

## ==========================
## Eureka Discovery Client
## ==========================
## Points to your running Eureka Server instance
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
## Tells this service to register itself with Eureka
#eureka.client.register-with-eureka=true
## Tells this service to download the registry cache so OpenFeign can look up other services
#eureka.client.fetch-registry=true
## Optional: Period in seconds the client sends heartbeats to server (default is 30)
#eureka.instance.lease-renewal-interval-in-seconds=30

# ==========================
# OpenFeign Configurations
# ==========================
# Global timeouts for all Feign clients (in milliseconds)
feign.client.config.default.connect-timeout=5000
feign.client.config.default.read-timeout=5000
# Configures Feign to log the basic request/response metrics
feign.client.config.default.logger-level=basic

# ==========================
# Swagger
# ==========================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ==========================
# Logging
# ==========================
logging.level.org.springframework=INFO
logging.level.root=INFO
level.com.rideHub.platform=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
# Added logging for your OpenFeign package to monitor inter-service communication
level.com.rideHub.platform.client=DEBUG

# ==========================
# JWT
# ==========================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
