spring.application.name=payment-service

# ==========================
# Database Configuration
# ==========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# Hibernate / JPA
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==========================
# Server
# ==========================
server.port=8085

# ==========================
# Swagger
# ==========================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ==========================
# Logging
# ==========================
logging.level.org.springframework=INFO
logging.level.root=INFO
level.com.rideHub.platform=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
# Added logging for your OpenFeign package to monitor inter-service communication
level.com.rideHub.platform.client=DEBUG

# ==========================
# JWT
# ==========================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000


ride.service.url=http://localhost:8084

payment.retry.max-attempts=3
payment.retry.delay=1000

payment.timeout=5000

# Retry
resilience4j.retry.instances.paymentGateway.max-attempts=3
resilience4j.retry.instances.paymentGateway.wait-duration=2s

# Time Limiter
resilience4j.timelimiter.instances.paymentGateway.timeout-duration=5s

# Circuit Breaker
resilience4j.circuitbreaker.instances.paymentGateway.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paymentGateway.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.paymentGateway.sliding-window-size=10
resilience4j.circuitbreaker.instances.paymentGateway.wait-duration-in-open-state=30s

# ==================================
# Resilience4j Circuit Breaker
# ==================================

resilience4j.circuitbreaker.instances.paymentGateway.registerHealthIndicator=true

resilience4j.circuitbreaker.instances.paymentGateway.slidingWindowSize=5

resilience4j.circuitbreaker.instances.paymentGateway.minimumNumberOfCalls=5

resilience4j.circuitbreaker.instances.paymentGateway.failureRateThreshold=50

resilience4j.circuitbreaker.instances.paymentGateway.waitDurationInOpenState=10s

resilience4j.circuitbreaker.instances.paymentGateway.permittedNumberOfCallsInHalfOpenState=2

resilience4j.circuitbreaker.instances.paymentGateway.automaticTransitionFromOpenToHalfOpenEnabled=true


management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers
management.endpoint.health.show-details=always



#kafka configurations
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=payment-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.ridehub.paymentservice.kafka.dto

